### ISSUE TITLE
Add a Namespace

### ISSUE THREAD

**Issue by SethArchambault** [sphido/routing#1]
Love the simplicity of this, but seems like a Namespace would of "Router" would be useful for making the dependency clear in the code.

Thoughts?

**Comment by OzzyCzech** [comment]
Ok, there are mostly common names like `error()`

**Comment by OzzyCzech** [comment]
closed by 581c0de08a88178687bf03c0c2ac59b44b372293

**Comment by SethArchambault** [comment]
😃
